# Generated by Django 4.2.5 on 2024-01-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escola", "0002_matricula"),
    ]

    operations = [
        migrations.CreateModel(
            name="Iris",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sepalLength", models.DecimalField(decimal_places=2, max_digits=5)),
                ("sepalWidth", models.DecimalField(decimal_places=2, max_digits=5)),
                ("petalLength", models.DecimalField(decimal_places=2, max_digits=5)),
                ("petalWidth", models.DecimalField(decimal_places=2, max_digits=5)),
                ("variety", models.CharField(max_length=20)),
            ],
        ),
    ]
